### ISSUE TITLE
Paper or references for this code

### ISSUE THREAD

**Issue by SalihaAlmalki** [AlirezaAbedinii/ImageCaptioning#1]
Hello, I am very interested in your work, I want to know if there is a paper for this code. or any references that you used to build your model. Thank you

**Comment by AlirezaAbedinii** [comment]
Hi, thank you for your interest in my work.
This code is my bachelor's final project, and there are many references.
However, the main reference for the code is the paper below. I hope it
helps.
" Improving Image Captioning with Conditional Generative Adversarial Nets"

**Comment by Nooor2023** [comment]
Hello
Sorry if I am bothering you 
I’m very interested in the Image captioning field
I read This paper 
" Improving Image Captioning with Conditional Generative Adversarial Nets ", and as you mentioned above it is the main for your code
I’m very interested in your code also I want to implement the model in this paper using the flickr8 dataset. 
So, I will be thankful to you if I find answers to my questions

1- Did you implement the model as it is explained in the paper or there is a difference between them, I main you use RL to update the CNN and RNN or just one of them by the feedback from the discriminator and language evaluator as I understand in your code
2- In the paper, there is an ensemble of 4 CNN-GAN and 4 RNN-GAN, have you implemented it in your work?
3- Also, which baseline algorithms and methods you used? I see you used the inception v3 model
but have you used the bottom-up or top-down mechanism and SCST as the training method?
4- Can I say your code like the main source for this paper?

Kindly if possible, I hope you to share with me your methodology and results it is important to me and it will help me to learn about the model that you used in your work and to gain more knowledge and experience about image captioning with GAN for my project

I'm sorry and thank you
